# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Coding\python\Solve-Reconstruction\UI\alg_import.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AlgWindow(object):
    def setupUi(self, AlgWindow):
        AlgWindow.setObjectName("AlgWindow")
        AlgWindow.resize(1293, 742)
        self.centralwidget = QtWidgets.QWidget(AlgWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 1181, 51))
        self.widget.setObjectName("widget")
        self.minButton = QtWidgets.QPushButton(self.widget)
        self.minButton.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.minButton.setText("")
        self.minButton.setObjectName("minButton")
        self.closeButton = QtWidgets.QPushButton(self.widget)
        self.closeButton.setGeometry(QtCore.QRect(1130, 10, 41, 41))
        self.closeButton.setText("")
        self.closeButton.setObjectName("closeButton")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.id = QtWidgets.QLabel(self.widget)
        self.id.setGeometry(QtCore.QRect(70, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.save_btn = QtWidgets.QPushButton(self.widget)
        self.save_btn.setGeometry(QtCore.QRect(990, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.id_2 = QtWidgets.QLabel(self.widget)
        self.id_2.setGeometry(QtCore.QRect(530, 10, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.id_2.setFont(font)
        self.id_2.setObjectName("id_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(50, 70, 211, 651))
        self.widget_2.setObjectName("widget_2")
        self.oll_btn = QtWidgets.QPushButton(self.widget_2)
        self.oll_btn.setGeometry(QtCore.QRect(0, 0, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.oll_btn.setFont(font)
        self.oll_btn.setObjectName("oll_btn")
        self.pll_btn = QtWidgets.QPushButton(self.widget_2)
        self.pll_btn.setGeometry(QtCore.QRect(0, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        self.pll_btn.setFont(font)
        self.pll_btn.setObjectName("pll_btn")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(260, 70, 971, 651))
        self.widget_3.setObjectName("widget_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 10, 931, 631))
        self.stackedWidget.setObjectName("stackedWidget")
        self.oll_page = QtWidgets.QWidget()
        self.oll_page.setObjectName("oll_page")
        self.oll_table = QtWidgets.QTableWidget(self.oll_page)
        self.oll_table.setGeometry(QtCore.QRect(0, 0, 931, 631))
        self.oll_table.setObjectName("oll_table")
        self.oll_table.setColumnCount(2)
        self.oll_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.oll_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.oll_table.setHorizontalHeaderItem(1, item)
        self.stackedWidget.addWidget(self.oll_page)
        self.pll_page = QtWidgets.QWidget()
        self.pll_page.setObjectName("pll_page")
        self.pll_table = QtWidgets.QTableWidget(self.pll_page)
        self.pll_table.setGeometry(QtCore.QRect(0, 0, 931, 631))
        self.pll_table.setObjectName("pll_table")
        self.pll_table.setColumnCount(3)
        self.pll_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.pll_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pll_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pll_table.setHorizontalHeaderItem(2, item)
        self.stackedWidget.addWidget(self.pll_page)
        AlgWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlgWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AlgWindow)

    def retranslateUi(self, AlgWindow):
        _translate = QtCore.QCoreApplication.translate
        AlgWindow.setWindowTitle(_translate("AlgWindow", "Algorithm"))
        self.id.setText(_translate("AlgWindow", "TextLabel"))
        self.save_btn.setText(_translate("AlgWindow", "Save"))
        self.id_2.setText(_translate("AlgWindow", "Algorithm Editor"))
        self.oll_btn.setText(_translate("AlgWindow", "OLL"))
        self.pll_btn.setText(_translate("AlgWindow", "PLL"))
        item = self.oll_table.horizontalHeaderItem(0)
        item.setText(_translate("AlgWindow", "OLL"))
        item = self.oll_table.horizontalHeaderItem(1)
        item.setText(_translate("AlgWindow", "Algorithm"))
        item = self.pll_table.horizontalHeaderItem(0)
        item.setText(_translate("AlgWindow", "Name"))
        item = self.pll_table.horizontalHeaderItem(1)
        item.setText(_translate("AlgWindow", "PLL"))
        item = self.pll_table.horizontalHeaderItem(2)
        item.setText(_translate("AlgWindow", "Algorithm"))
